import { CardProps } from '@/components/Card/Card';
import { CardListProps } from '@/components/CardList/CardList';
import { CardVisibilityType } from '@/interfaces/Card';

export const card: CardProps = {
  id: 1,
  src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png',
  createdBy: 'Alex',
  creationTimestamp: Date.now(),
  modificationTimestamp: Date.now(),
  title: 'Awesome card about React',
  description: 'Very long card description about created card',
  topics: ['programming'],
  tags: ['react', 'card', 'first card'],
  visibility: CardVisibilityType.ONLY_YOU,
  likes: 10,
  views: 10,
};

export const cards: CardListProps = {
  children: [
    card,
    {
      id: 2,
      src: 'https://upload.wikimedia.org/wikipedia/commons/4/49/Redux.png',
      createdBy: 'Alex',
      creationTimestamp: Date.now(),
      modificationTimestamp: Date.now(),
      title: 'Awesome card about Redux',
      description: 'Very long card description about created card',
      topics: ['programming'],
      tags: ['Redux', 'card'],
      visibility: CardVisibilityType.ONLY_YOU,
      likes: 10,
      views: 10,
    },
    {
      id: 3,
      src: 'https://www.typescriptlang.org/images/branding/two-longform.svg',
      createdBy: 'Alex',
      creationTimestamp: Date.now(),
      modificationTimestamp: Date.now(),
      title: 'Awesome card about Typescript',
      description: 'Very long card description about created card',
      topics: ['programming'],
      tags: ['Typescript', 'card'],
      visibility: CardVisibilityType.ONLY_YOU,
      likes: 10,
      views: 10,
    },
    {
      id: 4,
      src: 'https://www.w3schools.com/css/img_forest.jpg',
      createdBy: 'Alex',
      creationTimestamp: Date.now(),
      modificationTimestamp: Date.now(),
      title: 'Card about forest',
      description: 'Very long card description about created card',
      topics: ['travelling'],
      tags: ['forest', 'card', 'nature'],
      visibility: CardVisibilityType.ONLY_YOU,
      likes: 10,
      views: 10,
    },
    {
      id: 5,
      src: 'https://www.w3schools.com/css/img_mountains.jpg',
      createdBy: 'Alex',
      creationTimestamp: Date.now(),
      modificationTimestamp: Date.now(),
      title: 'Card about Mountains',
      description: 'Very long card description about created card',
      topics: ['travelling'],
      tags: ['mountains', 'card', 'nature'],
      visibility: CardVisibilityType.ONLY_YOU,
      likes: 10,
      views: 10,
    },
  ],
};
