import { type CardDetails } from '@/interfaces/Card';

export const cardDetails: CardDetails = {
  id: '1',
  imgSrc:
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png',
  createdBy: 'Alex',
  creationTimestamp: Date.now(),
  modificationTimestamp: Date.now(),
  description: 'Very long card description about React card',
  collections: ['programming'],
  tags: ['React', 'card', 'first card'],
  publicDomain: false,
  likes: 10,
  views: 10,
};

export const cardDetailsList: CardDetails[] = [
  cardDetails,
  {
    id: '2',
    imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/4/49/Redux.png',
    createdBy: 'Alex',
    creationTimestamp: Date.now(),
    modificationTimestamp: Date.now(),
    description: 'Awesome card about Redux',
    collections: ['programming'],
    tags: ['Redux', 'card'],
    publicDomain: false,
    likes: 10,
    views: 10,
  },
  {
    id: '3',
    imgSrc: 'https://www.typescriptlang.org/images/branding/two-longform.svg',
    createdBy: 'Alex',
    creationTimestamp: Date.now(),
    modificationTimestamp: Date.now(),
    description: 'Awesome card about Typescript',
    collections: ['programming'],
    tags: ['Typescript', 'card'],
    publicDomain: false,
    likes: 10,
    views: 10,
  },
  {
    id: '4',
    imgSrc: 'https://www.w3schools.com/css/img_forest.jpg',
    createdBy: 'Alex',
    creationTimestamp: Date.now(),
    modificationTimestamp: Date.now(),
    description: 'Card about forest',
    collections: ['nature'],
    tags: ['forest', 'card'],
    publicDomain: false,
    likes: 10,
    views: 10,
  },
  {
    id: '5',
    imgSrc: 'https://www.w3schools.com/css/img_mountains.jpg',
    createdBy: 'Alex',
    creationTimestamp: Date.now(),
    modificationTimestamp: Date.now(),
    description: 'Card about Mountains',
    collections: ['nature'],
    tags: ['mountains', 'card'],
    publicDomain: false,
    likes: 10,
    views: 10,
  },
];
